# Generated by Django 3.2.8 on 2021-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationotp',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
